### *Podemos rodar às segundas-feiras já que as partidas da liga são jogadas aos domingos*

In [1]:
import pandas as pd
from functions import clube_id_e_sessao, pega_dados, conecta_ao_db

In [2]:
sessao, club_id= clube_id_e_sessao()

Clube ID: 79085

### Informações gerais dos jogos

In [3]:
# Conecta ao banco de dados
db= conecta_ao_db('dados_sokker.db')
curs= db.cursor()

#Pega informações únicas das partidas já adicionadas para que não sejam inseridos valores duplicados na base
matches = pd.read_sql_query("SELECT * FROM matches", db)

ids= matches['matchID'].unique()
data_esperada= matches['dateExpected'].unique()
data_iniciada= matches['dateStarted'].unique()

In [4]:
# Id do clube a serem pegas as informações
id_clube= club_id

# Pegando informações das partidas retirando aquelas que já foram pegas
url= f'https://sokker.org/xml/matches-team-{club_id}.xml'
df_matches= pega_dados(url, sessao, search= 'match')

#Retirando valores nulos (partidas ainda não jogadas) e duplicados (partidas já adicionadas na base)
df_matches.dropna(inplace= True)

query= 'matchID not in @ids and dateExpected not in @data_esperada and dateStarted not in @data_iniciada'

# Retirando colunas que não salvaremos as informações
df_matches.drop(columns= ['homeTeamName', 'awayTeamName'], 
                inplace= True)

#df_matches= pd.concat([matches, df_matches])

df_matches= df_matches.query(query)
df_matches

,matchID,homeTeamID,awayTeamID,leagueID,round,season,week,day,dateExpected,dateStarted,homeTeamScore,awayTeamScore,supporters,weather,isFinished
34,44478507,99421,79085,61041,4,4,1213,6,2026-10-16 19:33,2026-10-16 19:33,0,0,33407,4,1
35,44756138,8821,79085,51530,0,0,1214,0,2026-10-17 19:30,2026-10-17 19:30,7,0,7690,6,1
36,44613152,79085,31312,1342,7,76,1214,1,2026-10-18 21:58,2026-10-18 21:58,1,3,11837,5,1
37,44757456,40922,79085,3,0,0,1214,2,2026-10-19 23:29,2026-10-19 23:29,0,3,3873,5,1
38,44761579,56373,79085,51530,0,0,1214,3,2026-10-20 19:35,2026-10-20 19:35,1,5,3761,4,1
39,44613164,79085,79193,1342,8,76,1214,4,2026-10-21 21:58,2026-10-21 21:58,5,0,17985,6,1

In [5]:
if len(df_matches) > 0:
    
    # Adiciona dados à tabela
    df_matches.to_sql('matches', con=db, if_exists='append', index= False)

In [6]:
#df_matches = pd.read_sql_query("SELECT * FROM matches", db)
len(df_matches)

6

### Estatísticas dos jogos

In [7]:
#Pega informações únicas das estatísticas já adicionadas para que não sejam inseridos valores duplicados na base
stats = pd.read_sql_query("SELECT * FROM matchStats", db)

ids= stats['matchID'].unique()
team= stats['teamID'].unique()
terco_defensivo= stats['timeOnHalf'].unique()
posse_de_bola= stats['timePossession'].unique()

In [8]:
#lista que guardará as estatísticas de cada partida
list_stats= list()

# Pegando estatísticas

for ID in df_matches['matchID'].unique():
    
    url= f'https://sokker.org/xml/match-{ID}.xml'
    df= pega_dados(url, sessao, search= 'teamStats')
    df['matchID']= ID
    list_stats.append(df)
    


df_stats= pd.concat([stats for stats in list_stats])

# Retirando valores nulos (partidas ainda não jogadas) e duplicados (partidas já adicionadas na base)

df_stats.dropna(inplace= True)

query= 'matchID not in @ids and teamID not in @team and timeOnHalf not in @terco_defensivo and timePossession not in @posse_de_bola'

df_stats= df_stats.query(query)

df_stats

,teamID,timeOnHalf,timePossession,offsides,shoots,fouls,yellowCards,redCards,tacticName,ratingScoring,ratingPassing,ratingDefending,matchID
0,99421,37823,43136,0,5,2,1,0,78.03,8,10,9,44478507
1,79085,32129,26816,0,1,5,2,0,5-4-1-DR,7,9,10,44478507
0,8821,14449,34570,6,21,1,0,0,3-1-2-2-2,12,11,9,44756138
1,79085,56071,35950,6,1,7,3,0,4-4-2c,7,8,11,44756138
0,79085,34422,34656,1,6,2,1,0,5-4-1-DRCH,8,8,11,44613152
1,31312,35534,35300,0,15,1,0,0,Jesus is God.,12,9,9,44613152
0,40922,25944,29197,0,7,1,0,0,52w2i,6,7,7,44757456
1,79085,44019,40766,2,9,3,1,0,4-4-2c,7,7,8,44757456
0,56373,43769,31665,0,3,6,4,0,obrona Czestocho,8,7,8,44761579
1,79085,26186,38290,0,18,0,0,0,3-4-3-EX,10,8,9,44761579
0,79085,29302,41248,1,14,0,0,0,4-4-2cDO,9,9,9,44613164
1,79193,41130,29184,0,1,4,0,0,RONALDO,4,5,5,44613164

In [9]:
# Adicionando informações se houver alguma nova
if len(df_stats) > 0:
    
    # Adiciona dados à tabela
    df_stats.to_sql('matchStats', con=db, if_exists='append', index= False)

In [10]:
# Conferindo
stats = pd.read_sql_query("SELECT * FROM matchStats", db)
len(stats)

2502

### Estatísticas da Liga

In [11]:
#Pega informações ligas já adicionadas para que não sejam inseridos valores duplicados na base
league_stats = pd.read_sql_query("SELECT * FROM leagueStats", db)

ids= league_stats['leagueID'].unique()
team= league_stats['teamID'].unique()
rodada=  league_stats['round'].unique()

In [12]:
#Pegar o id da liga desejada entrando na liga na página do sokker
league_id= 1349

url= f'https://sokker.org/xml/league-{league_id}.xml'
df_league_stats= pega_dados(url, sessao, search= 'teams', tree_top= True)

In [13]:
df_league_stats['leagueID']= league_id
df_league_stats

,teamID,round,points,wins,draws,losses,goalsScored,goalsLost,rankTotal,leagueID
0,78671,8,18,5,3,0,39,5,18534039005008,1349
1,79560,8,17,5,2,1,26,4,17522026005004,1349
2,89569,8,17,5,2,1,25,4,17521025005009,1349
3,48018,8,16,5,1,2,31,11,16520031005006,1349
4,78751,8,15,4,3,1,22,3,15519022004007,1349
5,123021,8,15,4,3,1,22,5,15517022004011,1349
6,124139,8,12,4,0,4,17,30,12487017004005,1349
7,79473,8,8,2,2,4,10,24,8486010002002,1349
8,48541,8,7,2,1,5,10,28,7482010002003,1349
9,79320,8,6,2,0,6,11,42,6469011002012,1349
10,23775,8,3,1,0,7,8,29,3479008001010,1349
11,90348,8,1,0,1,7,6,42,1464006000001,1349

In [14]:
# Adicionando informações 
if len(df_league_stats) > 0:
    
    # Adiciona dados à tabela
    df_league_stats.to_sql('leagueStats', con=db, if_exists='append', index= False)

league_stats = pd.read_sql_query("SELECT * FROM leagueStats", db)
len(league_stats)

### Liga informação geral

In [15]:
#Pega informações das ligas já adicionadas para que não sejam inseridos valores duplicados na base
leagues = pd.read_sql_query("SELECT * FROM league", db)

ids= leagues['leagueID'].unique()
league_name= leagues['name'].unique()

In [16]:
#Pegando dados da liga
df_league= pega_dados(url, sessao, search= 'info')

#Retirando coluna que não será utilizada
df_league.drop(columns= ['userID', 'round'], inplace= True)

#Retirando valores duplicados (se as estatísticas já tiverem sido adicionadas na base)
query= 'leagueID not in @ids and name not in @league_name'
df_league= df_league.query(query)

df_league

Empty DataFrame
Columns: [leagueID, name, countryID, division, season, type, isOfficial, isCup]
Index: []

In [17]:
# Adicionando informações se for uma liga ainda não adicionada
if len(df_league) > 0:
    
    # Adiciona dados à tabela
    df_league.to_sql('league', con=db, if_exists='append', index= False)

In [18]:
league = pd.read_sql_query("SELECT * FROM league", db)
len(league)

4

In [19]:
# Salvando alterações
db.commit()

# Fechando conexão com a base de dados
db.close()